
GET http://localhost:3000

###

GET http://localhost:3000/teste

###

POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "nome": "Joel Santos",
    "telefone": "40028922",
    "idade": "18"
}